import type { Metadata } from 'next'
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import SessionProvider from "@/provider/sessionProvider";
import Login from "@/components/Login";
import "./globals.css";
import { authOptions } from "@/utils/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Google Map Marker",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="bg-[#2bae66c2]">{children}</div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
